# Convert the cif file generated by protenix to pdb file that can be read by rosetta
# Adjust the last N atom into last GLY residue and change the name to NT to avoid auto-termination


import sys
from Bio.PDB import MMCIFParser, PDBIO

from Bio.PDB import PDBParser, MMCIFParser, PDBIO

def convert_cif_to_pdb(cif_file, pdb_file):
    """
    Convert a CIF file to a PDB file.
    Args:
        cif_file: Path to the input CIF file.
        pdb_file: Path to the output PDB file.
    """
    parser = MMCIFParser(QUIET=True)
    structure = parser.get_structure("structure", cif_file)
    io = PDBIO()
    io.set_structure(structure)
    io.save(pdb_file)

def edit_last_3rd_line(pdb_file):
    """
    Edit the line at the last 3rd position in a PDB file.
    Args:
        pdb_file: Path to the PDB file to edit.
    """
    with open(pdb_file, "r") as f:
        lines = f.readlines()

    # Modify the line at the last 3rd position
    target_index = len(lines) - 3
    if lines[target_index].startswith("ATOM"):
        lines[target_index] = lines[target_index].replace(" N ", " NT", 1).replace(" NH2 ", " GLY ").replace("10 ", " 9 ")

    # Write the modified lines back to the PDB file
    with open(pdb_file, "w") as f:
        f.writelines(lines)



if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python cif2pdb.py input.cif output.pdb")
        sys.exit(1)
    cif_file = sys.argv[1]
    pdb_file = sys.argv[2]
    convert_cif_to_pdb(cif_file, pdb_file)
    # edit_last_3rd_line(pdb_file)

