# Extract all the score generated by Rosetta

import sys

def extract_scores(filename):
    results = []
    with open(filename) as f:
        for line in f:
            if line.startswith("SCORE:") and not line.startswith("SCORE: total_score"):
                parts = line.strip().split()
                total_score = float(parts[1])
                name = parts[-1]
                results.append((name, total_score))
    return results

def main():
    filename = sys.argv[1] if len(sys.argv) > 1 else "your_file.txt"
    results = extract_scores(filename)
    with open("energy.txt", "w") as out_file:
        for name, score in results:
            out_file.write(f"{name}\t{score}\n")

if __name__ == "__main__":
    main()
